feat: re-add core contract
tansawit/homora-ib-swap pull request #1
Opened 2021-03-03 04:44 UTC by tansawit

2021-03-03 05:16 UTC, GriphookETH requested changes

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    IUniswapV2Router02 public uniswapRouter;
Can make this constant and initialize the value here (no need to do it in constructor)

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    function supported(address token) public returns (bool) {
This function can be `pure`. Also can do `return token == ... || token == ... || ...;`

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +            underlying.safeApprove(UNISWAP_ROUTER_ADDRESS, underlyingBalance);
I think it's simpler to just do approve inifinite in constructor.

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    address private constant IBDAIV2 =
should we worry about adding more ib tokens in the future?

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    address private constant IBETHV2 =
Making this public does not hurt imo

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    function getEstimateAmountOut(
Estimated / Expected

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    function getEstimateAmountOut(
amounts

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +        uint256 amountIn
There should be slippage control here (`amountOutMin`)

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    function path(uint256 order, address token)
I think it's less confusing to make this function takes two addresses (one will be WETH, the other will be token) instead of `order` and `token`

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +            IERC20(safeboxOut.uToken()).approve(
Same here for approve

2021-03-03 05:16 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    receive() external payable {}
Should assert that msg.sender must be either safeBoxETH or router

2021-03-03 10:42 UTC, GriphookETH requested changes

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    IUniswapV2Router02 public uniswapRouter =
public constant

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    address UNISWAP_ROUTER_ADDRESS = 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D;
pubic constant

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +            if (!isIBToken[tokens[idx]] && tokens[idx] != IBETHV2) {
safer to do `require(!isIBToken[tokens[idx]] && tokens[idx] != IBETHV2, '...')`

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +            underlyingTokenIn = uniswapRouter.WETH();
should initialize weth as constant or immutable to save gas and not repeatedly to call the view function

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +        internal
let's make it public

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +        address[] memory path;
can declare this in `returns (address[] memory path)`

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +                amountOutMin,
use 0

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +        return outputAmount;
require outputAmount >= amountOutMin

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +                amountOutMin,
ditto

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +                amountOutMin,
ditto

2021-03-03 10:42 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +                safeboxOut.balanceOf(address(this))
use `outputAmount` to save unnecessary calls

2021-03-04 06:11 UTC, GriphookETH requested changes

2021-03-04 06:11 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +    address public constant IBETHV2 =
ibETHV2 address can also be immutable and come as a parameter

2021-03-04 06:11 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +            underlyingBalance = underlying.balanceOf(address(this));
For clarity, I think we should do `underlyingBalance = address(this).balance` in else case

2021-03-04 06:11 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +            uniswapRouter.swapExactETHForTokens{value: address(this).balance}(
can use `underlyingBalance`

2021-03-04 06:11 UTC, GriphookETH commented on contracts/HomoraIBSwap.sol
> +            IERC20(safeboxOut.uToken()).approve(
Approve here should not be needed because we already did inifinite approve?

2021-03-04 06:11 UTC, GriphookETH commented on tests/test_revert.py
> +SAFEBOX_ABI = [
This should not be needed. Can you use `interfaces.ISafeBox.at(...)` instead of `Contract.from_abi`?

2021-03-04 07:16 UTC, GriphookETH approved these changes
looks good minus test script

2021-04-08 10:39 UTC, tansawit commented
@GriphookETH will add full test suite in another PR. <3

2021-04-08 10:39 UTC, merged

2021-05-14 13:28 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +    function addIBTokens(address[] memory tokens) external onlyGov {
can change to `calldata`

2021-05-14 13:28 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +    function addIBTokens(address[] memory tokens) external onlyGov {
can change to `calldata`

2021-05-14 13:29 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +            IERC20(safebox.uToken()).safeApprove(
`address uToken = safebox.uToken()` to optimize gas

2021-05-14 13:33 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +            underlyingTokenIn = uniswapRouter.WETH();
Use `WETH`

2021-05-14 13:34 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +        if (tokenIn == IBETHV2) {
Can also shorten into 

`underlyingTokenIn = tokenIn == IBETHV2 ? WETH : SafeBox(tokenIn).uToken();`

2021-05-14 13:36 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +        address underlyingTokenIn;
Should also check `tokenIn != tokenOut`

2021-05-14 13:37 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +        }
This is redundant to the above `if-else`. Should be able to optimize this.

2021-05-14 13:39 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +        uint256 tokenAmount =
Can just return without variable assignment

2021-05-14 13:39 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +        uint256 ibTokenAmount =
ditto

2021-05-14 13:41 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +        return
Need to check `tokenIn != tokenOut` cuz `getPath` does not check

2021-05-14 13:41 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +        SafeBox safeboxIn = SafeBox(tokenIn);
No need for this variable.

2021-05-14 13:48 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +            safeboxOut.transfer(msg.sender, outputAmount);
Since this is the same across if and else, should just move out of the clauses

2021-05-14 13:51 UTC, n1punp commented on contracts/HomoraIBSwap.sol
> +        }
Perhaps a better way to do this is to work with WETH when swapping, so you only need `swapExactTokensForTokens`. Then you just need to check if `tokenIn` is ETH related --> Then withdraw ETH -> wrap to WETH.

If `tokenOut` is ETH related --> unwrap WETH -> deposit to ibETH.

2022-01-31 20:20 UTC, Pencab reviewed
contracts/HomoraIBSwap.sol